spring:
  security:
    basic:
      enabled: false
  application:
    name: oauth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://103.40.27.214:3306/auth?characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 6546321
    hikari:
      auto-commit: true
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      pool-name: oauth-pool
      connection-test-query: select 1
      max-lifetime: 28740000
  # rabbitmq:
  #    host: localhost
  #    virtual-host: /
  #    username: guest
  #    password: guest
  #    template:
  #      retry:
  #        enabled: true
  #        initial-interval: 10000ms
  #        max-interval: 300000ms
  #        multiplier: 2
  #      exchange: ECLOUD_PAY_EXCHANGE
  #    publisher-confirms: true
  redis:
    host: 103.40.27.214
server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
logging:
  path: /Log/system_log.log
  level:
    xatu.zsl: debug
    org.springfromework.web: debug
    com.auth.authserver.api.dao: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
